### ISSUE TITLE
leader discovery

### ISSUE THREAD

**Issue by harmw** [mesosphere/mesos_exporter#23]
Looking at the README, one is supposed to run _one_ exporter with the `-master` flag pointed to the *current* master. What happens in the event of that master crashing and some other node becoming master?

The _old_ deprecated exporter could discover the master, is that something that will be merged in this exporter - or can I just run the master exporter on all masters in my cluster?

**Comment by StephanErb** [comment]
The expected usage is that you run one exporter next to each master. This  means each master will be scraped individually. 

If you are interested only in the leading master, you can have a look at the `mesos_master_elected` metric: 

```
mesos_master_elected{cluster="us-tirefire1",instance="master1.example.org:9091",job="mesos-master"} 0
mesos_master_elected{cluster="us-tirefire1",instance="master2.example.org:9091",job="mesos-master"} 0
mesos_master_elected{cluster="us-tirefire1",instance="master3.example.org:9091",job="mesos-master"} 1
```

Scraping each master individually provides some great flexibility. For example, you could use this to do alerting on the overall state of your cluster:
```
ALERT MesosMasterNoLeader
  IF sum(mesos_master_elected{job="mesos-master"}) == 0
  FOR 5m
  LABELS {severity="critical"}
  ANNOTATIONS {description="There is no leading mesos-master", runbook="Good luck!", summary="No mesos-master leading!"}

ALERT MesosMasterTooManyMasters
  IF sum(mesos_master_elected{job="mesos-master"}) > 1
  FOR 5m
  LABELS {severity="critical"}
  ANNOTATIONS {description="There should be exactly one leader!", runbook="Good luck!", summary="Multiple mesos-masters leading!"}
```

If you look at an individual metric like `mesos_master_mem` you will notice that the leading master is reporting the true value and the other masters are reporting 0. You can select the metric from the master either via a join in PromQL or via an aggregation. In most cases I therefore use a form of the following:
    
    # Query
    max(mesos_master_mem) without (instance)
    # Result
    {cluster="devcluster",job="mesos-master",type="used"}	1779200
    {cluster="devcluster",job="mesos-master",type="free"}	4662717


Hope this gets you started!

**Comment by harmw** [comment]
Yeah definitely! The README states I should be running just _one_ exporter, so perhaps that can be cleared in the docs. Thanks 👍

**Comment by lloesche** [comment]
If you're running this with Mesos-DNS you can just point it to leader.mesos and it'll always scrape the leading master.
