### ISSUE TITLE
Exporter still exports even if Mesos is unavailable

### ISSUE THREAD

**Issue by amerkel2** [mesosphere/mesos_exporter#24]
When Mesos is not available, messages like `Get http://<IP>:5051/metrics/snapshot: dial tcp <IP>:5051: getsockopt: connection refused` appear in the log, but the exporter stays up and just does not export the Mesos metrics. This makes it hard to detect such failures.

**Comment by brianmulder** [comment]
The metrics that remain do however contain reference to the failed/error attempts at scraping for metrics.

    `mesos_collector_errors_total`

**Comment by brianmulder** [comment]
I.e. this behaviour is desirable.

**Comment by StephanErb** [comment]
https://prometheus.io/docs/instrumenting/writing_exporters/#failed-scrapes states:


> Failed scrapes
> 
> There are currently two patterns for failed scrapes where the application you’re talking to doesn’t respond or has other problems.
> 
> The first is to return a 5xx error.
> 
> The seconds is to have an myexporter_up (e.g. haproxy_up) variable that’s 0/1 depending on whether the scrape worked.
> 
> The latter is better where there’s still some useful metrics you can get even with a failed scrape, such as the haproxy exporter providing process stats. The former is a tad easier for users to deal with, as up works in the usual way (though you can’t distinguish between the exporter being down and the application being down).


This exporter is using a third option that is not part of the official documentation: It uses a counter that is incremented for each scape failure. In general though, it works. I am therefore closing this issue as "works for me".

To make it easier for users to get started, I might add a few example alerts though.
