### ISSUE TITLE
mesos_slave_task_state_time metrics accumulate over lifetime of service

### ISSUE THREAD

**Issue by byxorna** [mesosphere/mesos_exporter#25]
I have been seeing the exporter get slower and slower over time (months of uptime), due to a seeming accumulation of label combinations for the `mesos_slave_task_state_time` metric. It appears that the exporter is caching and exporting every task's state over the exporters lifetime (including stale tasks no longer tracked by the masters), not just those exposed via the Mesos stats API. Eventually, the `/metrics` payload gets so large and expensive to scrape that scrapes time out. 

Restarting the mesos_exporter every once in a while is a valid workaround, but thought I would open a ticket to track regardless. @discordianfish

**Comment by StephanErb** [comment]
There is a option `-ignoreCompletedFrameworkTasks` to disable that problematic metric. The corresponding pull request was merged on Friday but has not made it into a 'release', yet. 

We should probably consider to make that the default or drop the metric entirely.

**Comment by byxorna** [comment]
@StephanErb does that only ignore tasks from a framework that is completed, or ignore all tasks that are completed, regardless of framework status? The tasks I am seeing persist are from a framework that has not completed (marathon), so stripping out task statuses from completed frameworks wouldnt seem to help here at all (if i understand it correctly)

**Comment by StephanErb** [comment]
Basically, the option will completely drop the metric `mesos_slave_task_state_time` for all frameworks.

**Comment by byxorna** [comment]
Seems like thats pretty reasonable to make that default, if having it enabled comes with serious penalties down the road (like your prometheus machine falling over, or scrape payloads becoming too large to scrape, etc).

**Comment by discordianfish** [comment]
The exporter should probably use ConstMetric instead, this would also make sure you don't have those 'stale' metrics around. Here is an example what would need to get changed: https://github.com/prometheus/node_exporter/pull/285/files

**Comment by StephanErb** [comment]
I have dropped the metric entirely in 032c93c6c872eef933caf78346244425950112ea.
