### ISSUE TITLE
Wont build against latest prometheus client_golang

### ISSUE THREAD

**Issue by byxorna** [mesosphere/mesos_exporter#26]
https://github.com/prometheus/client_golang/commit/2fee50beaa152342e8347c41edf2202c3bd5f858 seems to have broken the mesos_exporter build. Because this project doesn't vendorize dependencies, I was unable to build by a simple `go get ...`. Either explicit versions of transitive dependencies should be vendorized, or declared in a godeps file (or equivalent)

**Comment by StephanErb** [comment]
This has been fixed by the referenced commit.
