### ISSUE TITLE
Use GitHub release for installing Mesos Exporter

### ISSUE THREAD

**Issue by jlrigau** [mesosphere/mesos_exporter#36]
In order to install a specific version of Mesos Exporter without using Docker or `go get`, it could be good to have a way to manage releases for each new version of the exporter, via GitHub releases for example.

[Prometheus Utility Tool (aka promu)](https://github.com/prometheus/promu) is a tool for helping the build and the release of a Prometheus exporter.

Is it planned to use it?

**Comment by StephanErb** [comment]
That worked better than expected! :) First test release is available here: https://github.com/mesosphere/mesos_exporter/releases 

I will now start doing a major version release using this.
