### ISSUE TITLE
master not showing the correct stats

### ISSUE THREAD

**Issue by rabun788** [mesosphere/mesos_exporter#39]
I have four Mesos environments running and an exporter for each environment. For some reason, one environment is not giving the exporter the correct information.

This is running as a docker container on CENTOS 7.

Mesos Version:
```
Cluster:MDI_MESOS 
Server:<ip>:5050
Version:1.1.0
Built: 6 months ago by ubuntu 
Started: a week ago 
Elected: a week ago
```

`curl http://<mesos-master>:5050/state | jq .`
```
{
  "version": "1.1.0",
  "git_sha": "a44b077ea0df54b77f05550979e1e97f39b15873",
  "git_tag": "1.1.0",
  "build_date": "2016-11-16 01:30:23",
  "build_time": 1479259823,
  "build_user": "ubuntu",
  "start_time": 1494343403.05936,
  "elected_time": 1494483984.0112,
  "id": "f4385139-58dd-4c33-87d9-cb2f2d6c1c67",
  "pid": "master@<ip>:5050",
  "hostname": "fqdn.com",
  "activated_slaves": 66,
  "deactivated_slaves": 0,
  "leader": "master@1<ip>:5050",
  "leader_info": {
    "id": "f4385139-58dd-4c33-87d9-cb2f2d6c1c67",
    "pid": "master@<ip>:5050",
    "port": 5050,
    "hostname": "fqdn.com"
  },
```
mesos_exporter showing:
```
# HELP mesos_master_elected 1 if master is elected leader, 0 if not
# TYPE mesos_master_elected gauge
mesos_master_elected 0
```

My docker file looks like:

```
FROM alpine:3.4

EXPOSE 9110

RUN addgroup exporter \
 && adduser -S -G exporter exporter

COPY . /go/src/github.com/mesosphere/mesos_exporter

RUN apk --update add ca-certificates \
 && apk --update add --virtual build-deps go git \
 && cd /go/src/github.com/mesosphere/mesos_exporter \
 && GOPATH=/go go get \
 && GOPATH=/go go build -o /bin/mesos-exporter \
 && apk del --purge build-deps \
 && rm -rf /go/bin /go/pkg /var/cache/apk/*

USER exporter
#ENTRYPOINT [ "/bin/mesos-exporter" ]
CMD [ "/bin/mesos-exporter","-master","http://mesos-master.com:5050" ]
```

Let me know if i can provide any other information.

**Comment by StephanErb** [comment]
The `mesos_exporter`, like most other Prometheus exporters, assumes you run one exporter per instance. This means you have to run one exporter next to each master. 

The leading master should return `mesos_master_elected 1` whereas the non-leading ones should report `mesos_master_elected 0`. You can verify this if you query the `/metrics/snapshot` endpoint of the respective masters.

The `/state` endpoint you have mentioned above is slightly different: It always redirects to the leading master and can thus be confusing as it does not give you the details of the instance you are currently querying, but of a _different_ one.

**Comment by rabun788** [comment]
Thanks Stephan. 

I deployed this in Mesos thinking that the master i provided would forward the request to the elected master. Sounds like I should deploy 5 more in order to get every master (currently have 5) monitored. 

Is there a specific reason we can't pass all the masters into the `-master` flag? Comma separated perhaps?

I deploy the slave monitors with Ansible. 

```---
  - name: Get Primary IP
    shell: hostname --ip-address
    register: ip_address
    changed_when: False
    tags:
      - mesos-exporter

  - name: Slave Mesos-Exporter
    docker_container:
      image: "{{docker_repo_v2}}/mesos-exporter-slave:blue"
      pull: True
      ports:
        - "9110:9110"
      network_mode: host
      restart_policy: always
      name: "mesos-exporter-slave"
      command: "/bin/mesos-exporter -slave http://{{ ip_address.stdout }}:5051"
      state: started
    ignore_errors: True
    tags:
      - mesos-exporter
```
It sounds like i need to do that with the masters now.  
Thanks for you help.
