### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by StephanErb** [mesosphere/mesos_exporter#4]
Please add a license. Otherwise nobody can really use it.

**Comment by keis** [comment]
Bump @discordianfish :cat:

**Comment by discordianfish** [comment]
I know, I know - @s-urbaniak @lloesche @spacejam Anyone of you guys can help with this?

**Comment by s-urbaniak** [comment]
@discordianfish mentioned this internally, apparently nothing happened, let me reping, sorry about that folks!

**Comment by lloesche** [comment]
fixed

**Comment by keis** [comment]
Thank you :)

**Comment by discordianfish** [comment]
Awesome, thanks! :)
