### ISSUE TITLE
Versioned stable docker tags

### ISSUE THREAD

**Issue by dharmab** [mesosphere/mesos_exporter#43]
We'd like to deploy this exporter in our environment. However, the `mesosphere/mesos_exporter` image on Docker Hub only has a `latest` tag, and our policy does not allow us to deploy containers tagged `latest` in case of future breaking changes.

Some versioned tags would allow us to pin a specific version and test new versions before upgrading.

**Comment by jamessoubry** [comment]
+1

**Comment by StephanErb** [comment]
I have to admit I don't know how or by whom that docker images was uploaded. As I don't work for Mesosphere I cannot help you, unfortunately.

**Comment by dharmab** [comment]
Looks like someone saw this issue, because there's now a `v1.0.0` tag on the image. 😄
