### ISSUE TITLE
Unclear semantics of metric `mesos_slave_task_state_time`

### ISSUE THREAD

**Issue by StephanErb** [mesosphere/mesos_exporter#5]
The exporter when running with `-master` is exporting metrics named `mesos_slave_task_state_time`.

Example:

```
mesos_slave_task_state_time{  
   executor="thermos-1454666700002-xxx-devel-service-14427-0-f4d47c26-bd2f-4c01-be3f-299ef0b59ea9",
   framework="20151001-085346-58917130-5050-37976-0000",
   name="nobody/devel/service-14427",
   slave="1454666700002-nobody-devel-service-14427-0-f4d47c26-bd2f-4c01-be3f-299ef0b59ea9",
   state="TASK_FAILED",
   task="20160118-141153-92471562-5050-6270-S15"
} 1.45466670079993e+09
```

The underlying `state.json` contains:

```
{  
   executor_id:"thermos-1454666700002-nobody-devel-service-14427-0-f4d47c26-bd2f-4c01-be3f-299ef0b59ea9",
   framework_id:"20151001-085346-58917130-5050-37976-0000",
   id:"1454666700002-nobody-devel-service-14427-0-f4d47c26-bd2f-4c01-be3f-299ef0b59ea9",
   labels:[  

   ],
   name:"nobody/devel/service-14427",
   resources:{  
      cpus:1,
      disk:8192,
      mem:4096,
      ports:"[31029-31029, 31560-31560]"
   },
   slave_id:"20160118-141153-92471562-5050-6270-S15",
   state:"TASK_FAILED",
   statuses:[  
      {  
         state:"TASK_STARTING",
         timestamp:1454666700.79993
      },
      {  
         state:"TASK_RUNNING",
         timestamp:1454666701.53248
      },
      {  
         state:"TASK_FAILED",
         timestamp:1454666905.24761
      }
   ]
},
```

It seems like that the metrics is returning the **start time** for all **completed** tasks. What's the usecase for this? In addition, there is a small inconsistency: slave and task ID are swapped.

Would be create if someone could explain the intentions of this one.

**Comment by StephanErb** [comment]
Interesting enough, we had a monitoring incident due to this: Due to the sheer number of `mesos_slave_task_state_time` metrics the exporter could not be scarped in a timely fashion.

**Comment by magicrobotmonkey** [comment]
I have the same problem, It's slowly killing prometheus as it waits for this to be scraped

**Comment by magicrobotmonkey** [comment]
https://github.com/magicrobotmonkey/mesos_exporter/commit/7ccd7090eef63c6c06140c54ef381cbe012fd9cf

I removed this function and things have been chugging along nicely without it. Like the OP, I'm not clear on what the intended purpose of this metric is, or even how I'd visualize it.
